import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import Center from '../components/Center'
import Player from '../components/Player'
import styles from '../styles/Home.module.css'
import { getSession } from 'next-auth/react'

export default function Home() {
  return (
    <div className='h-screen overflow-hidden'>
      <Head>
        <title>Shpeetify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex'>
        <Sidebar />
        <Center />
      </main>
      <div className="sticky bottom-0">
          <Player />
        </div>
    </div>
  )
}

export async function getServerSideProps(context){
  const session = await getSession(context);
  return{
    props: {
      session
  },
}}